--*************************************************************************************
--*                            UNCLASSIFIED                                           *
--*************************************************************************************
--*                            BAE SYSTEMS PROPRIETARY                                *
--*************************************************************************************
--*          Export Control Restrictions: NONE                                        *
--*************************************************************************************
--*                                                                                   *
--*               Copyright 2023 BAE Systems. All Rights Reserved.                    *
--*                                                                                   *
--*************************************************************************************
--*                                                                                   *
--* No contract-specific restrictions are in place for this code-generated file.      *
--*                                                                                   *
--*************************************************************************************
--*                                                                                   *
--* File Name:               TAGS_registration.adb
--* Drawing Number:          Refer to release documentation                           *
--* Version:                 As detailed by Configuration Management System           *
--* Version Date:            As detailed by Configuration Management System           *
--* Creation Date:           As detailed by Configuration Management System           *
--* Section/Unit:            Refer to release documentation                           *
--* Description:             
--*                          Template for domain registrations 
--* Comments:                Header written by header.macro                           *
--*                           
--*                                                                                   *
--*************************************************************************************
--*                            SUPPLEMENTAL INFORMATION                               *
--*                            ------------------------                               *
--*  OVERVIEW                                                                         *
--*  --------                                                                         *
--*
--*  ERROR HANDLING                                                                   *
--*  --------------                                                                   *
--*  None                                                                             *
--*                                                                                   *
--*  SAFETY         : None                                                            *
--*  ------                                                                           *
--*                                                                                   *
--*  BUILD INFORMATION                                                                *
--* -----------------                                                                 *
--*                                                                                   *
--*  Project Key Letter : TSV2
--*  Project Version    : 0
--*  Build Set          : 0
--*                                                                                   *
--*  Build Target       : Dos
--*  Clock Type         : INTERNAL
--*  Debugging is       : Off
--*  Trace is           : Off
--*                                                                                   *
--*  
--*  
--*  
--*  
--*  
--*************************************************************************************
--*  COMPONENTS CONTAINED WITHIN THIS FILE                                            *
--*  package body TAGS_Registration 
--*    procedure Register_All 
--*
--*************************************************************************************
--  MODIFICATION RECORD
--  --------------------
--     NAME     DATE             ECR No            MODIFICATION
--
--    jmm     13/03/00        008998/9SR056     Change super-sub specification name to include the domain key
--                                              letter. Note that the change locations are NOT marked in the code 
--                                              body to avoid multiple entries being generated by loops in the
--                                              final source code. Code changes can be identified using the
--                                              clearcase differences tool.
--
--    jmm     10/05/00        PILOT_0000_0460   Change order of A/B groupings for A_End_Is_Multiple/B_End_Is_Single
--                                              reflexive relationships
--
--    jmm     03/10/00        PILOT_0000_0600   Changes for issue 3.0.0 in accordance with ATN_037_03_01.
--
--    db      27/07/01        PILOT_0000_0230   Coding Standards transgressions fixed
--
--    db      21/08/01        PILOT_0000_1431   Associative A end multiple, B end single incorrect
--
--    db      07/02/02        SRLE100001428     Rename file to match package definition.
--
--    db      26/03/02        SRLE100002907     Remove invocation to Root_Object.Initialise_List and
--                                              <Domain_Key_Letter>_Rel_<Domain_Relationship.Relationship_No>.Initialise;
--
--    ANF     04/07/06        001798 9SR056     Archetype language reformatted
--
-- **************************************************************************************
with Root_Object;

with TAGS_Comms_Registration;

--================================================================================== 
with Root_Object.TAGS.AAO;
with Root_Object.TAGS.APSO;
with Root_Object.TAGS.APAOOO;
with Root_Object.TAGS.RD;
with Root_Object.TAGS.CHECK;
with Root_Object.TAGS.TD;
with Root_Object.TAGS.AAAOOO;
with Root_Object.TAGS.AAAOTO;
with Root_Object.TAGS.APAOTO;
with Root_Object.TAGS.STO;
with Root_Object.TAGS.MTO;
with Root_Object.TAGS.ATSO;
with Root_Object.TAGS.ATMO;
with Root_Object.TAGS.TM_LEFT;
with Root_Object.TAGS.TM_RIGHT;
with Root_Object.TAGS.TS_ASSOC;
with Root_Object.TAGS.TAG_SUPER;
with Root_Object.TAGS.SUB_ONE;
with Root_Object.TAGS.SUB_TWO;
with Root_Object.TAGS.SGR;
with Root_Object.TAGS.MGR;
with Root_Object.TAGS.ATML;
with Root_Object.TAGS.ATMR;
with Root_Object.TAGS.ATSASSOC;
with Root_Object.TAGS.ATSUPER;
with Root_Object.TAGS.ATSUBONE;
with Root_Object.TAGS.ATSUBTWO;
with Root_Object.TAGS.ATSUBTHREE;
with Root_Object.TAGS.MSGR;
with Root_Object.TAGS.ASO;
with Root_Object.TAGS.ASSO;
with Root_Object.TAGS.AMSO;
with Root_Object.TAGS.JM;

--================================================================================== 
with TAGS_Rel_R4;
with TAGS_R4_Specification;
with TAGS_Rel_R6;
with TAGS_R6_Specification;
with TAGS_Rel_R1;
with TAGS_Rel_R2;
with TAGS_Rel_R3;
with TAGS_Rel_R5;

--================================================================================== 
   
with Ada.Tags;

package body TAGS_Registration is

--================================================================================== 

   procedure Register_All is

   begin

--==================================================================================
      -- Relationships for TAGS domain to register:
      -- Relationship R4 is Super Sub
      TAGS_Rel_R4.Register_Super_End_Class (Root_Object.TAGS.TAG_SUPER.TAGS_TAG_SUPER_Type'tag);
      TAGS_Rel_R4.Register_Sub_End_Relationship_Write (Root_Object.TAGS.TAG_SUPER.Put_R4_Sub'access);
      TAGS_Rel_R4.Register_Sub_End_Relationship_Read  (Root_Object.TAGS.TAG_SUPER.Get_R4_Sub'access);
  
      TAGS_Rel_R4.Register_Super_End_Relationship_Write (TAGS_R4_Specification.Subtype_Write_Accessor'access);
      TAGS_Rel_R4.Register_Super_End_Relationship_Read  (TAGS_R4_Specification.Subtype_Read_Accessor'access);
--==================================================================================
      -- Relationships for TAGS domain to register:
      -- Relationship R6 is Super Sub
      TAGS_Rel_R6.Register_Super_End_Class (Root_Object.TAGS.ATSUPER.TAGS_ATSUPER_Type'tag);
      TAGS_Rel_R6.Register_Sub_End_Relationship_Write (Root_Object.TAGS.ATSUPER.Put_R6_Sub'access);
      TAGS_Rel_R6.Register_Sub_End_Relationship_Read  (Root_Object.TAGS.ATSUPER.Get_R6_Sub'access);
  
      TAGS_Rel_R6.Register_Super_End_Relationship_Write (TAGS_R6_Specification.Subtype_Write_Accessor'access);
      TAGS_Rel_R6.Register_Super_End_Relationship_Read  (TAGS_R6_Specification.Subtype_Read_Accessor'access);
--==================================================================================
      -- Relationships for TAGS domain to register:
      -- Relationship R1 is Simple 
      TAGS_Rel_R1.Register_A_End_Class (Root_Object.TAGS.MTO.TAGS_MTO_Type'tag);
      TAGS_Rel_R1.Register_B_End_Class (Root_Object.TAGS.STO.TAGS_STO_Type'tag);

      TAGS_Rel_R1.Register_A_End_Relationship_Write (Root_Object.TAGS.STO.Put_R1_B'access);
      TAGS_Rel_R1.Register_A_End_Relationship_Read  (Root_Object.TAGS.STO.Get_R1_B'access);
      TAGS_Rel_R1.Register_B_End_Relationship_Write (Root_Object.TAGS.MTO.Put_R1_A'access);
      TAGS_Rel_R1.Register_B_End_Relationship_Read  (Root_Object.TAGS.MTO.Get_R1_A'access);

--==================================================================================
      -- Relationships for TAGS domain to register:
      -- Relationship R2 is Simple 
      TAGS_Rel_R2.Register_A_End_Class (Root_Object.TAGS.ATMO.TAGS_ATMO_Type'tag);
      TAGS_Rel_R2.Register_B_End_Class (Root_Object.TAGS.ATSO.TAGS_ATSO_Type'tag);

      TAGS_Rel_R2.Register_A_End_Relationship_Write (Root_Object.TAGS.ATSO.Put_R2_B'access);
      TAGS_Rel_R2.Register_A_End_Relationship_Read  (Root_Object.TAGS.ATSO.Get_R2_B'access);
      TAGS_Rel_R2.Register_B_End_Relationship_Write (Root_Object.TAGS.ATMO.Put_R2_A'access);
      TAGS_Rel_R2.Register_B_End_Relationship_Read  (Root_Object.TAGS.ATMO.Get_R2_A'access);

--==================================================================================
      -- Relationships for TAGS domain to register:
      -- Relationship R3 is Associative
      TAGS_Rel_R3.Register_M1_End_Class (Root_Object.TAGS.TM_RIGHT.TAGS_TM_RIGHT_Type'tag);
      TAGS_Rel_R3.Register_M2_End_Class (Root_Object.TAGS.TM_LEFT.TAGS_TM_LEFT_Type'tag);
      TAGS_Rel_R3.Register_Associative_End_Class (Root_Object.TAGS.TS_ASSOC.TAGS_TS_ASSOC_Type'tag);
      --
--==================================================================================
      -- Relationships for TAGS domain to register:
      -- Relationship R5 is Associative
      TAGS_Rel_R5.Register_M1_End_Class (Root_Object.TAGS.ATMR.TAGS_ATMR_Type'tag);
      TAGS_Rel_R5.Register_M2_End_Class (Root_Object.TAGS.ATML.TAGS_ATML_Type'tag);
      TAGS_Rel_R5.Register_Associative_End_Class (Root_Object.TAGS.ATSASSOC.TAGS_ATSASSOC_Type'tag);
      --

      -- Relationships for Comms to register:
      TAGS_Comms_Registration.Register_Comms;

   end Register_All;

end TAGS_Registration;

