--*************************************************************************************
--*                            UNCLASSIFIED                                           *
--*************************************************************************************
--*                            BAE SYSTEMS PROPRIETARY                                *
--*************************************************************************************
--*          Export Control Restrictions: NONE                                        *
--*************************************************************************************
--*                                                                                   *
--*               Copyright 2023 BAE Systems. All Rights Reserved.                    *
--*                                                                                   *
--*************************************************************************************
--*                                                                                   *
--* No contract-specific restrictions are in place for this code-generated file.      *
--*                                                                                   *
--*************************************************************************************
--*                                                                                   *
--* File Name:               Creation_Deletion_registration.adb
--* Drawing Number:          Refer to release documentation                           *
--* Version:                 As detailed by Configuration Management System           *
--* Version Date:            As detailed by Configuration Management System           *
--* Creation Date:           As detailed by Configuration Management System           *
--* Section/Unit:            Refer to release documentation                           *
--* Description:             
--*                          Template for domain registrations 
--* Comments:                Header written by header.macro                           *
--*                           
--*                                                                                   *
--*************************************************************************************
--*                            SUPPLEMENTAL INFORMATION                               *
--*                            ------------------------                               *
--*  OVERVIEW                                                                         *
--*  --------                                                                         *
--*
--*  ERROR HANDLING                                                                   *
--*  --------------                                                                   *
--*  None                                                                             *
--*                                                                                   *
--*  SAFETY         : None                                                            *
--*  ------                                                                           *
--*                                                                                   *
--*  BUILD INFORMATION                                                                *
--* -----------------                                                                 *
--*                                                                                   *
--*  Project Key Letter : TSV2
--*  Project Version    : 0
--*  Build Set          : 0
--*                                                                                   *
--*  Build Target       : Dos
--*  Clock Type         : INTERNAL
--*  Debugging is       : Off
--*  Trace is           : Off
--*                                                                                   *
--*  
--*  
--*  
--*  
--*  
--*************************************************************************************
--*  COMPONENTS CONTAINED WITHIN THIS FILE                                            *
--*  package body Creation_Deletion_Registration 
--*    procedure Register_All 
--*
--*************************************************************************************
--  MODIFICATION RECORD
--  --------------------
--     NAME     DATE             ECR No            MODIFICATION
--
--    jmm     13/03/00        008998/9SR056     Change super-sub specification name to include the domain key
--                                              letter. Note that the change locations are NOT marked in the code 
--                                              body to avoid multiple entries being generated by loops in the
--                                              final source code. Code changes can be identified using the
--                                              clearcase differences tool.
--
--    jmm     10/05/00        PILOT_0000_0460   Change order of A/B groupings for A_End_Is_Multiple/B_End_Is_Single
--                                              reflexive relationships
--
--    jmm     03/10/00        PILOT_0000_0600   Changes for issue 3.0.0 in accordance with ATN_037_03_01.
--
--    db      27/07/01        PILOT_0000_0230   Coding Standards transgressions fixed
--
--    db      21/08/01        PILOT_0000_1431   Associative A end multiple, B end single incorrect
--
--    db      07/02/02        SRLE100001428     Rename file to match package definition.
--
--    db      26/03/02        SRLE100002907     Remove invocation to Root_Object.Initialise_List and
--                                              <Domain_Key_Letter>_Rel_<Domain_Relationship.Relationship_No>.Initialise;
--
--    ANF     04/07/06        001798 9SR056     Archetype language reformatted
--
-- **************************************************************************************
with Root_Object;

with Creation_Deletion_Comms_Registration;

--================================================================================== 
with Root_Object.Creation_Deletion.objA;
with Root_Object.Creation_Deletion.objB;
with Root_Object.Creation_Deletion.objC;
with Root_Object.Creation_Deletion.coloured;
with Root_Object.Creation_Deletion.objD;
with Root_Object.Creation_Deletion.flavoured;
with Root_Object.Creation_Deletion.objCS;
with Root_Object.Creation_Deletion.fandc;
with Root_Object.Creation_Deletion.dr;
with Root_Object.Creation_Deletion.objTS;
with Root_Object.Creation_Deletion.enemy;
with Root_Object.Creation_Deletion.drenemy;
with Root_Object.Creation_Deletion.RD;

--================================================================================== 
with Creation_Deletion_Rel_R1;
with Creation_Deletion_Rel_R2;

--================================================================================== 
   
with Ada.Tags;

package body Creation_Deletion_Registration is

--================================================================================== 

   procedure Register_All is

   begin

--==================================================================================
      -- Relationships for Creation_Deletion domain to register:
      -- Relationship R1 is Associative
      Creation_Deletion_Rel_R1.Register_M1_End_Class (Root_Object.Creation_Deletion.flavoured.Creation_Deletion_flavoured_Type'tag);
      Creation_Deletion_Rel_R1.Register_M2_End_Class (Root_Object.Creation_Deletion.coloured.Creation_Deletion_coloured_Type'tag);
      Creation_Deletion_Rel_R1.Register_Associative_End_Class (Root_Object.Creation_Deletion.fandc.Creation_Deletion_fandc_Type'tag);
      --
--==================================================================================
      -- Relationships for Creation_Deletion domain to register:
      -- Relationship R2 is Associative
      Creation_Deletion_Rel_R2.Register_Single_End_Class (Root_Object.Creation_Deletion.dr.Creation_Deletion_dr_Type'tag);
      Creation_Deletion_Rel_R2.Register_Multiple_End_Class (Root_Object.Creation_Deletion.enemy.Creation_Deletion_enemy_Type'tag);
      Creation_Deletion_Rel_R2.Register_Associative_End_Class (Root_Object.Creation_Deletion.drenemy.Creation_Deletion_drenemy_Type'tag);
      --

      -- Relationships for Comms to register:
      Creation_Deletion_Comms_Registration.Register_Comms;

   end Register_All;

end Creation_Deletion_Registration;

