--*************************************************************************************
--*                            UNCLASSIFIED                                           *
--*************************************************************************************
--*                            BAE SYSTEMS PROPRIETARY                                *
--*************************************************************************************
--*          Export Control Restrictions: NONE                                        *
--*************************************************************************************
--*                                                                                   *
--*               Copyright 2023 BAE Systems. All Rights Reserved.                    *
--*                                                                                   *
--*************************************************************************************
--*                                                                                   *
--* No contract-specific restrictions are in place for this code-generated file.      *
--*                                                                                   *
--*************************************************************************************
--*                                                                                   *
--* File Name:               TT_registration.adb
--* Drawing Number:          Refer to release documentation                           *
--* Version:                 As detailed by Configuration Management System           *
--* Version Date:            As detailed by Configuration Management System           *
--* Creation Date:           As detailed by Configuration Management System           *
--* Section/Unit:            Refer to release documentation                           *
--* Description:             
--*                          Template for domain registrations 
--* Comments:                Header written by header.macro                           *
--*                           
--*                                                                                   *
--*************************************************************************************
--*                            SUPPLEMENTAL INFORMATION                               *
--*                            ------------------------                               *
--*  OVERVIEW                                                                         *
--*  --------                                                                         *
--*
--*  ERROR HANDLING                                                                   *
--*  --------------                                                                   *
--*  None                                                                             *
--*                                                                                   *
--*  SAFETY         : None                                                            *
--*  ------                                                                           *
--*                                                                                   *
--*  BUILD INFORMATION                                                                *
--* -----------------                                                                 *
--*                                                                                   *
--*  Project Key Letter : TSV2
--*  Project Version    : 0
--*  Build Set          : 0
--*                                                                                   *
--*  Build Target       : Dos
--*  Clock Type         : INTERNAL
--*  Debugging is       : Off
--*  Trace is           : Off
--*                                                                                   *
--*  
--*  
--*  
--*  
--*  
--*************************************************************************************
--*  COMPONENTS CONTAINED WITHIN THIS FILE                                            *
--*  package body TT_Registration 
--*    procedure Register_All 
--*
--*************************************************************************************
--  MODIFICATION RECORD
--  --------------------
--     NAME     DATE             ECR No            MODIFICATION
--
--    jmm     13/03/00        008998/9SR056     Change super-sub specification name to include the domain key
--                                              letter. Note that the change locations are NOT marked in the code 
--                                              body to avoid multiple entries being generated by loops in the
--                                              final source code. Code changes can be identified using the
--                                              clearcase differences tool.
--
--    jmm     10/05/00        PILOT_0000_0460   Change order of A/B groupings for A_End_Is_Multiple/B_End_Is_Single
--                                              reflexive relationships
--
--    jmm     03/10/00        PILOT_0000_0600   Changes for issue 3.0.0 in accordance with ATN_037_03_01.
--
--    db      27/07/01        PILOT_0000_0230   Coding Standards transgressions fixed
--
--    db      21/08/01        PILOT_0000_1431   Associative A end multiple, B end single incorrect
--
--    db      07/02/02        SRLE100001428     Rename file to match package definition.
--
--    db      26/03/02        SRLE100002907     Remove invocation to Root_Object.Initialise_List and
--                                              <Domain_Key_Letter>_Rel_<Domain_Relationship.Relationship_No>.Initialise;
--
--    ANF     04/07/06        001798 9SR056     Archetype language reformatted
--
-- **************************************************************************************
with Root_Object;

with TT_Comms_Registration;

--================================================================================== 
with Root_Object.TT.T;
with Root_Object.TT.TS;
with Root_Object.TT.BT;
with Root_Object.TT.U;
with Root_Object.TT.RD;
with Root_Object.TT.DT;
with Root_Object.TT.RT;
with Root_Object.TT.TR;

--================================================================================== 
with TT_Rel_R2;
with TT_R2_Specification;
with TT_Rel_R1;
with TT_Rel_R3;
with TT_Rel_R4;

--================================================================================== 
   
with Ada.Tags;

package body TT_Registration is

--================================================================================== 

   procedure Register_All is

   begin

--==================================================================================
      -- Relationships for TT domain to register:
      -- Relationship R2 is Super Sub
      TT_Rel_R2.Register_Super_End_Class (Root_Object.TT.T.TT_T_Type'tag);
      TT_Rel_R2.Register_Sub_End_Relationship_Write (Root_Object.TT.T.Put_R2_Sub'access);
      TT_Rel_R2.Register_Sub_End_Relationship_Read  (Root_Object.TT.T.Get_R2_Sub'access);
  
      TT_Rel_R2.Register_Super_End_Relationship_Write (TT_R2_Specification.Subtype_Write_Accessor'access);
      TT_Rel_R2.Register_Super_End_Relationship_Read  (TT_R2_Specification.Subtype_Read_Accessor'access);
--==================================================================================
      -- Relationships for TT domain to register:
      -- Relationship R1 is Simple 
      TT_Rel_R1.Register_A_End_Class (Root_Object.TT.TS.TT_TS_Type'tag);
      TT_Rel_R1.Register_B_End_Class (Root_Object.TT.T.TT_T_Type'tag);

      TT_Rel_R1.Register_A_End_Relationship_Write (Root_Object.TT.TS.Put_R1_B'access);
      TT_Rel_R1.Register_A_End_Relationship_Read  (Root_Object.TT.TS.Get_R1_B'access);
      TT_Rel_R1.Register_B_End_Relationship_Write (Root_Object.TT.T.Put_R1_A'access);
      TT_Rel_R1.Register_B_End_Relationship_Read  (Root_Object.TT.T.Get_R1_A'access);

--==================================================================================
      -- Relationships for TT domain to register:
      -- Relationship R3 is Simple 
      TT_Rel_R3.Register_A_End_Class (Root_Object.TT.TS.TT_TS_Type'tag);
      TT_Rel_R3.Register_B_End_Class (Root_Object.TT.RD.TT_RD_Type'tag);

      TT_Rel_R3.Register_A_End_Relationship_Write (Root_Object.TT.TS.Put_R3_B'access);
      TT_Rel_R3.Register_A_End_Relationship_Read  (Root_Object.TT.TS.Get_R3_B'access);
      TT_Rel_R3.Register_B_End_Relationship_Write (Root_Object.TT.RD.Put_R3_A'access);
      TT_Rel_R3.Register_B_End_Relationship_Read  (Root_Object.TT.RD.Get_R3_A'access);

--==================================================================================
      -- Relationships for TT domain to register:
      -- Relationship R4 is Reflexive
      TT_Rel_R4.Register_A_End_Class (Root_Object.TT.T.TT_T_Type'tag);
      TT_Rel_R4.Register_A_End_Role ("follows");
      TT_Rel_R4.Register_B_End_Class (Root_Object.TT.T.TT_T_Type'tag);
      TT_Rel_R4.Register_B_End_Role ("is_followed_by");

      TT_Rel_R4.Register_A_End_Relationship_Write (Root_Object.TT.T.Put_R4_B'access);
      TT_Rel_R4.Register_A_End_Relationship_Read  (Root_Object.TT.T.Get_R4_B'access);
      TT_Rel_R4.Register_B_End_Relationship_Write (Root_Object.TT.T.Put_R4_A'access);
      TT_Rel_R4.Register_B_End_Relationship_Read  (Root_Object.TT.T.Get_R4_A'access);

      -- Relationships for Comms to register:
      TT_Comms_Registration.Register_Comms;

   end Register_All;

end TT_Registration;

