--*************************************************************************************
--*                            UNCLASSIFIED                                           *
--*************************************************************************************
--*                            BAE SYSTEMS PROPRIETARY                                *
--*************************************************************************************
--*          Export Control Restrictions: NONE                                        *
--*************************************************************************************
--*                                                                                   *
--*               Copyright 2023 BAE Systems. All Rights Reserved.                    *
--*                                                                                   *
--*************************************************************************************
--*                                                                                   *
--* No contract-specific restrictions are in place for this code-generated file.      *
--*                                                                                   *
--*************************************************************************************
--*                                                                                   *
--* File Name:               Relationships_registration.adb
--* Drawing Number:          Refer to release documentation                           *
--* Version:                 As detailed by Configuration Management System           *
--* Version Date:            As detailed by Configuration Management System           *
--* Creation Date:           As detailed by Configuration Management System           *
--* Section/Unit:            Refer to release documentation                           *
--* Description:             
--*                          Template for domain registrations 
--* Comments:                Header written by header.macro                           *
--*                           
--*                                                                                   *
--*************************************************************************************
--*                            SUPPLEMENTAL INFORMATION                               *
--*                            ------------------------                               *
--*  OVERVIEW                                                                         *
--*  --------                                                                         *
--*
--*  ERROR HANDLING                                                                   *
--*  --------------                                                                   *
--*  None                                                                             *
--*                                                                                   *
--*  SAFETY         : None                                                            *
--*  ------                                                                           *
--*                                                                                   *
--*  BUILD INFORMATION                                                                *
--* -----------------                                                                 *
--*                                                                                   *
--*  Project Key Letter : TSV2
--*  Project Version    : 0
--*  Build Set          : 0
--*                                                                                   *
--*  Build Target       : Dos
--*  Clock Type         : INTERNAL
--*  Debugging is       : Off
--*  Trace is           : Off
--*                                                                                   *
--*  
--*  
--*  
--*  
--*  
--*************************************************************************************
--*  COMPONENTS CONTAINED WITHIN THIS FILE                                            *
--*  package body Relationships_Registration 
--*    procedure Register_All 
--*
--*************************************************************************************
--  MODIFICATION RECORD
--  --------------------
--     NAME     DATE             ECR No            MODIFICATION
--
--    jmm     13/03/00        008998/9SR056     Change super-sub specification name to include the domain key
--                                              letter. Note that the change locations are NOT marked in the code 
--                                              body to avoid multiple entries being generated by loops in the
--                                              final source code. Code changes can be identified using the
--                                              clearcase differences tool.
--
--    jmm     10/05/00        PILOT_0000_0460   Change order of A/B groupings for A_End_Is_Multiple/B_End_Is_Single
--                                              reflexive relationships
--
--    jmm     03/10/00        PILOT_0000_0600   Changes for issue 3.0.0 in accordance with ATN_037_03_01.
--
--    db      27/07/01        PILOT_0000_0230   Coding Standards transgressions fixed
--
--    db      21/08/01        PILOT_0000_1431   Associative A end multiple, B end single incorrect
--
--    db      07/02/02        SRLE100001428     Rename file to match package definition.
--
--    db      26/03/02        SRLE100002907     Remove invocation to Root_Object.Initialise_List and
--                                              <Domain_Key_Letter>_Rel_<Domain_Relationship.Relationship_No>.Initialise;
--
--    ANF     04/07/06        001798 9SR056     Archetype language reformatted
--
-- **************************************************************************************
with Root_Object;

with Relationships_Comms_Registration;

--================================================================================== 
with Root_Object.Relationships.objA;
with Root_Object.Relationships.objB;
with Root_Object.Relationships.RD;
with Root_Object.Relationships.objC;
with Root_Object.Relationships.objD;
with Root_Object.Relationships.objE;
with Root_Object.Relationships.objF;
with Root_Object.Relationships.OBJEF;
with Root_Object.Relationships.FL;
with Root_Object.Relationships.M;
with Root_Object.Relationships.objH;
with Root_Object.Relationships.objI;
with Root_Object.Relationships.MR;
with Root_Object.Relationships.TN;
with Root_Object.Relationships.MFR;
with Root_Object.Relationships.MRA;
with Root_Object.Relationships.objG;
with Root_Object.Relationships.MA;
with Root_Object.Relationships.LO;
with Root_Object.Relationships.RO;
with Root_Object.Relationships.MO;
with Root_Object.Relationships.assMR;
with Root_Object.Relationships.objLM;
with Root_Object.Relationships.objL;
with Root_Object.Relationships.objM;
with Root_Object.Relationships.objRM;
with Root_Object.Relationships.objO;
with Root_Object.Relationships.objDO;
with Root_Object.Relationships.objP;
with Root_Object.Relationships.objQ;
with Root_Object.Relationships.objR;
with Root_Object.Relationships.objLMRM;
with Root_Object.Relationships.objBM;
with Root_Object.Relationships.RAOA;
with Root_Object.Relationships.objSL1;
with Root_Object.Relationships.objSL2;
with Root_Object.Relationships.objSL3;
with Root_Object.Relationships.objSSL1;
with Root_Object.Relationships.objSSL2;
with Root_Object.Relationships.objSSL3;
with Root_Object.Relationships.objSSL4;
with Root_Object.Relationships.objSSSL1;
with Root_Object.Relationships.objSSSL2;
with Root_Object.Relationships.objSSL5;
with Root_Object.Relationships.objSSL6;
with Root_Object.Relationships.objSSL7;
with Root_Object.Relationships.objSSL8;
with Root_Object.Relationships.objSSL9;
with Root_Object.Relationships.objSSL10;
with Root_Object.Relationships.objSSL11;
with Root_Object.Relationships.objK;

--================================================================================== 
with Relationships_Rel_R9;
with Relationships_R9_Specification;
with Relationships_Rel_R26;
with Relationships_R26_Specification;
with Relationships_Rel_R27;
with Relationships_R27_Specification;
with Relationships_Rel_R29;
with Relationships_R29_Specification;
with Relationships_Rel_R30;
with Relationships_R30_Specification;
with Relationships_Rel_R31;
with Relationships_R31_Specification;
with Relationships_Rel_R28;
with Relationships_R28_Specification;
with Relationships_Rel_R1;
with Relationships_Rel_R3;
with Relationships_Rel_R5;
with Relationships_Rel_R11;
with Relationships_Rel_R13;
with Relationships_Rel_R18;
with Relationships_Rel_R19;
with Relationships_Rel_R20;
with Relationships_Rel_R21;
with Relationships_Rel_R22;
with Relationships_Rel_R2;
with Relationships_Rel_R4;
with Relationships_Rel_R6;
with Relationships_Rel_R7;
with Relationships_Rel_R8;
with Relationships_Rel_R10;
with Relationships_Rel_R12;
with Relationships_Rel_R14;
with Relationships_Rel_R15;
with Relationships_Rel_R16;
with Relationships_Rel_R17;
with Relationships_Rel_R23;
with Relationships_Rel_R32;

--================================================================================== 
   
with Ada.Tags;

package body Relationships_Registration is

--================================================================================== 

   procedure Register_All is

   begin

--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R9 is Super Sub
      Relationships_Rel_R9.Register_Super_End_Class (Root_Object.Relationships.objH.Relationships_objH_Type'tag);
      Relationships_Rel_R9.Register_Sub_End_Relationship_Write (Root_Object.Relationships.objH.Put_R9_Sub'access);
      Relationships_Rel_R9.Register_Sub_End_Relationship_Read  (Root_Object.Relationships.objH.Get_R9_Sub'access);
  
      Relationships_Rel_R9.Register_Super_End_Relationship_Write (Relationships_R9_Specification.Subtype_Write_Accessor'access);
      Relationships_Rel_R9.Register_Super_End_Relationship_Read  (Relationships_R9_Specification.Subtype_Read_Accessor'access);
--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R26 is Super Sub
      Relationships_Rel_R26.Register_Super_End_Class (Root_Object.Relationships.objL.Relationships_objL_Type'tag);
      Relationships_Rel_R26.Register_Sub_End_Relationship_Write (Root_Object.Relationships.objL.Put_R26_Sub'access);
      Relationships_Rel_R26.Register_Sub_End_Relationship_Read  (Root_Object.Relationships.objL.Get_R26_Sub'access);
  
      Relationships_Rel_R26.Register_Super_End_Relationship_Write (Relationships_R26_Specification.Subtype_Write_Accessor'access);
      Relationships_Rel_R26.Register_Super_End_Relationship_Read  (Relationships_R26_Specification.Subtype_Read_Accessor'access);
--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R27 is Super Sub
      Relationships_Rel_R27.Register_Super_End_Class (Root_Object.Relationships.objSL3.Relationships_objSL3_Type'tag);
      Relationships_Rel_R27.Register_Sub_End_Relationship_Write (Root_Object.Relationships.objSL3.Put_R27_Sub'access);
      Relationships_Rel_R27.Register_Sub_End_Relationship_Read  (Root_Object.Relationships.objSL3.Get_R27_Sub'access);
  
      Relationships_Rel_R27.Register_Super_End_Relationship_Write (Relationships_R27_Specification.Subtype_Write_Accessor'access);
      Relationships_Rel_R27.Register_Super_End_Relationship_Read  (Relationships_R27_Specification.Subtype_Read_Accessor'access);
--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R29 is Super Sub
      Relationships_Rel_R29.Register_Super_End_Class (Root_Object.Relationships.objSL3.Relationships_objSL3_Type'tag);
      Relationships_Rel_R29.Register_Sub_End_Relationship_Write (Root_Object.Relationships.objSL3.Put_R29_Sub'access);
      Relationships_Rel_R29.Register_Sub_End_Relationship_Read  (Root_Object.Relationships.objSL3.Get_R29_Sub'access);
  
      Relationships_Rel_R29.Register_Super_End_Relationship_Write (Relationships_R29_Specification.Subtype_Write_Accessor'access);
      Relationships_Rel_R29.Register_Super_End_Relationship_Read  (Relationships_R29_Specification.Subtype_Read_Accessor'access);
--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R30 is Super Sub
      Relationships_Rel_R30.Register_Super_End_Class (Root_Object.Relationships.objSL3.Relationships_objSL3_Type'tag);
      Relationships_Rel_R30.Register_Sub_End_Relationship_Write (Root_Object.Relationships.objSL3.Put_R30_Sub'access);
      Relationships_Rel_R30.Register_Sub_End_Relationship_Read  (Root_Object.Relationships.objSL3.Get_R30_Sub'access);
  
      Relationships_Rel_R30.Register_Super_End_Relationship_Write (Relationships_R30_Specification.Subtype_Write_Accessor'access);
      Relationships_Rel_R30.Register_Super_End_Relationship_Read  (Relationships_R30_Specification.Subtype_Read_Accessor'access);
--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R31 is Super Sub
      Relationships_Rel_R31.Register_Super_End_Class (Root_Object.Relationships.objSL3.Relationships_objSL3_Type'tag);
      Relationships_Rel_R31.Register_Sub_End_Relationship_Write (Root_Object.Relationships.objSL3.Put_R31_Sub'access);
      Relationships_Rel_R31.Register_Sub_End_Relationship_Read  (Root_Object.Relationships.objSL3.Get_R31_Sub'access);
  
      Relationships_Rel_R31.Register_Super_End_Relationship_Write (Relationships_R31_Specification.Subtype_Write_Accessor'access);
      Relationships_Rel_R31.Register_Super_End_Relationship_Read  (Relationships_R31_Specification.Subtype_Read_Accessor'access);
--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R28 is Super Sub
      Relationships_Rel_R28.Register_Super_End_Class (Root_Object.Relationships.objSSL2.Relationships_objSSL2_Type'tag);
      Relationships_Rel_R28.Register_Sub_End_Relationship_Write (Root_Object.Relationships.objSSL2.Put_R28_Sub'access);
      Relationships_Rel_R28.Register_Sub_End_Relationship_Read  (Root_Object.Relationships.objSSL2.Get_R28_Sub'access);
  
      Relationships_Rel_R28.Register_Super_End_Relationship_Write (Relationships_R28_Specification.Subtype_Write_Accessor'access);
      Relationships_Rel_R28.Register_Super_End_Relationship_Read  (Relationships_R28_Specification.Subtype_Read_Accessor'access);
--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R1 is Simple 
      Relationships_Rel_R1.Register_A_End_Class (Root_Object.Relationships.objA.Relationships_objA_Type'tag);
      Relationships_Rel_R1.Register_B_End_Class (Root_Object.Relationships.objB.Relationships_objB_Type'tag);

      Relationships_Rel_R1.Register_A_End_Relationship_Write (Root_Object.Relationships.objA.Put_R1_B'access);
      Relationships_Rel_R1.Register_A_End_Relationship_Read  (Root_Object.Relationships.objA.Get_R1_B'access);
      Relationships_Rel_R1.Register_B_End_Relationship_Write (Root_Object.Relationships.objB.Put_R1_A'access);
      Relationships_Rel_R1.Register_B_End_Relationship_Read  (Root_Object.Relationships.objB.Get_R1_A'access);

--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R3 is Simple 
      Relationships_Rel_R3.Register_A_End_Class (Root_Object.Relationships.objC.Relationships_objC_Type'tag);
      Relationships_Rel_R3.Register_B_End_Class (Root_Object.Relationships.objD.Relationships_objD_Type'tag);

      Relationships_Rel_R3.Register_B_End_Relationship_Write (Root_Object.Relationships.objC.Put_R3_B'access);
      Relationships_Rel_R3.Register_B_End_Relationship_Read  (Root_Object.Relationships.objC.Get_R3_B'access);
      Relationships_Rel_R3.Register_A_End_Relationship_Write (Root_Object.Relationships.objD.Put_R3_A'access);
      Relationships_Rel_R3.Register_A_End_Relationship_Read  (Root_Object.Relationships.objD.Get_R3_A'access);

--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R5 is Associative
      Relationships_Rel_R5.Register_M1_End_Class (Root_Object.Relationships.objE.Relationships_objE_Type'tag);
      Relationships_Rel_R5.Register_M2_End_Class (Root_Object.Relationships.objF.Relationships_objF_Type'tag);
      Relationships_Rel_R5.Register_Associative_End_Class (Root_Object.Relationships.OBJEF.Relationships_OBJEF_Type'tag);
      --
--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R11 is Reflexive
      Relationships_Rel_R11.Register_A_End_Class (Root_Object.Relationships.objG.Relationships_objG_Type'tag);
      Relationships_Rel_R11.Register_A_End_Role ("Has_a");
      Relationships_Rel_R11.Register_B_End_Class (Root_Object.Relationships.objG.Relationships_objG_Type'tag);
      Relationships_Rel_R11.Register_B_End_Role ("May_have");

      Relationships_Rel_R11.Register_A_End_Relationship_Write (Root_Object.Relationships.objG.Put_R11_B'access);
      Relationships_Rel_R11.Register_A_End_Relationship_Read  (Root_Object.Relationships.objG.Get_R11_B'access);
      Relationships_Rel_R11.Register_B_End_Relationship_Write (Root_Object.Relationships.objG.Put_R11_A'access);
      Relationships_Rel_R11.Register_B_End_Relationship_Read  (Root_Object.Relationships.objG.Get_R11_A'access);
--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R13 is Reflexive
      Relationships_Rel_R13.Register_A_End_Class (Root_Object.Relationships.objG.Relationships_objG_Type'tag);
      Relationships_Rel_R13.Register_A_End_Role ("Has_many");
      Relationships_Rel_R13.Register_B_End_Class (Root_Object.Relationships.objG.Relationships_objG_Type'tag);
      Relationships_Rel_R13.Register_B_End_Role ("Has_a");

      Relationships_Rel_R13.Register_A_End_Relationship_Write (Root_Object.Relationships.objG.Put_R13_A'access);
      Relationships_Rel_R13.Register_A_End_Relationship_Read  (Root_Object.Relationships.objG.Get_R13_A'access);
      Relationships_Rel_R13.Register_B_End_Relationship_Write (Root_Object.Relationships.objG.Put_R13_B'access);
      Relationships_Rel_R13.Register_B_End_Relationship_Read  (Root_Object.Relationships.objG.Get_R13_B'access);
--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R18 is Simple 
      Relationships_Rel_R18.Register_A_End_Class (Root_Object.Relationships.objB.Relationships_objB_Type'tag);
      Relationships_Rel_R18.Register_B_End_Class (Root_Object.Relationships.objM.Relationships_objM_Type'tag);

      Relationships_Rel_R18.Register_A_End_Relationship_Write (Root_Object.Relationships.objB.Put_R18_B'access);
      Relationships_Rel_R18.Register_A_End_Relationship_Read  (Root_Object.Relationships.objB.Get_R18_B'access);
      Relationships_Rel_R18.Register_B_End_Relationship_Write (Root_Object.Relationships.objM.Put_R18_A'access);
      Relationships_Rel_R18.Register_B_End_Relationship_Read  (Root_Object.Relationships.objM.Get_R18_A'access);

--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R19 is Associative
      Relationships_Rel_R19.Register_Single_End_Class (Root_Object.Relationships.objD.Relationships_objD_Type'tag);
      Relationships_Rel_R19.Register_Multiple_End_Class (Root_Object.Relationships.objO.Relationships_objO_Type'tag);
      Relationships_Rel_R19.Register_Associative_End_Class (Root_Object.Relationships.objDO.Relationships_objDO_Type'tag);
      --
--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R20 is Simple 
      Relationships_Rel_R20.Register_A_End_Class (Root_Object.Relationships.objQ.Relationships_objQ_Type'tag);
      Relationships_Rel_R20.Register_B_End_Class (Root_Object.Relationships.objP.Relationships_objP_Type'tag);

      Relationships_Rel_R20.Register_A_End_Relationship_Write (Root_Object.Relationships.objP.Put_R20_B'access);
      Relationships_Rel_R20.Register_A_End_Relationship_Read  (Root_Object.Relationships.objP.Get_R20_B'access);
      Relationships_Rel_R20.Register_B_End_Relationship_Write (Root_Object.Relationships.objQ.Put_R20_A'access);
      Relationships_Rel_R20.Register_B_End_Relationship_Read  (Root_Object.Relationships.objQ.Get_R20_A'access);

--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R21 is Simple 
      Relationships_Rel_R21.Register_A_End_Class (Root_Object.Relationships.objQ.Relationships_objQ_Type'tag);
      Relationships_Rel_R21.Register_B_End_Class (Root_Object.Relationships.objR.Relationships_objR_Type'tag);

      Relationships_Rel_R21.Register_B_End_Relationship_Write (Root_Object.Relationships.objQ.Put_R21_B'access);
      Relationships_Rel_R21.Register_B_End_Relationship_Read  (Root_Object.Relationships.objQ.Get_R21_B'access);
      Relationships_Rel_R21.Register_A_End_Relationship_Write (Root_Object.Relationships.objR.Put_R21_A'access);
      Relationships_Rel_R21.Register_A_End_Relationship_Read  (Root_Object.Relationships.objR.Get_R21_A'access);

--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R22 is Simple 
      Relationships_Rel_R22.Register_A_End_Class (Root_Object.Relationships.objR.Relationships_objR_Type'tag);
      Relationships_Rel_R22.Register_B_End_Class (Root_Object.Relationships.objP.Relationships_objP_Type'tag);

      Relationships_Rel_R22.Register_A_End_Relationship_Write (Root_Object.Relationships.objP.Put_R22_B'access);
      Relationships_Rel_R22.Register_A_End_Relationship_Read  (Root_Object.Relationships.objP.Get_R22_B'access);
      Relationships_Rel_R22.Register_B_End_Relationship_Write (Root_Object.Relationships.objR.Put_R22_A'access);
      Relationships_Rel_R22.Register_B_End_Relationship_Read  (Root_Object.Relationships.objR.Get_R22_A'access);

--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R2 is Reflexive
      Relationships_Rel_R2.Register_A_End_Class (Root_Object.Relationships.objG.Relationships_objG_Type'tag);
      Relationships_Rel_R2.Register_A_End_Role ("A_Large_relationship_role");
      Relationships_Rel_R2.Register_B_End_Class (Root_Object.Relationships.objG.Relationships_objG_Type'tag);
      Relationships_Rel_R2.Register_B_End_Role ("qwertyuiopasdfghjklzxcvbnmqwerty");

      Relationships_Rel_R2.Register_A_End_Relationship_Write (Root_Object.Relationships.objG.Put_R2_B'access);
      Relationships_Rel_R2.Register_A_End_Relationship_Read  (Root_Object.Relationships.objG.Get_R2_B'access);
      Relationships_Rel_R2.Register_B_End_Relationship_Write (Root_Object.Relationships.objG.Put_R2_A'access);
      Relationships_Rel_R2.Register_B_End_Relationship_Read  (Root_Object.Relationships.objG.Get_R2_A'access);
--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R4 is Reflexive
      Relationships_Rel_R4.Register_A_End_Class (Root_Object.Relationships.objG.Relationships_objG_Type'tag);
      Relationships_Rel_R4.Register_A_End_Role ("Has_many");
      Relationships_Rel_R4.Register_B_End_Class (Root_Object.Relationships.objG.Relationships_objG_Type'tag);
      Relationships_Rel_R4.Register_B_End_Role ("Has_a");

      Relationships_Rel_R4.Register_A_End_Relationship_Write (Root_Object.Relationships.objG.Put_R4_A'access);
      Relationships_Rel_R4.Register_A_End_Relationship_Read  (Root_Object.Relationships.objG.Get_R4_A'access);
      Relationships_Rel_R4.Register_B_End_Relationship_Write (Root_Object.Relationships.objG.Put_R4_B'access);
      Relationships_Rel_R4.Register_B_End_Relationship_Read  (Root_Object.Relationships.objG.Get_R4_B'access);
--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R6 is Simple 
      Relationships_Rel_R6.Register_A_End_Class (Root_Object.Relationships.FL.Relationships_FL_Type'tag);
      Relationships_Rel_R6.Register_B_End_Class (Root_Object.Relationships.M.Relationships_M_Type'tag);

      Relationships_Rel_R6.Register_A_End_Relationship_Write (Root_Object.Relationships.FL.Put_R6_B'access);
      Relationships_Rel_R6.Register_A_End_Relationship_Read  (Root_Object.Relationships.FL.Get_R6_B'access);
      Relationships_Rel_R6.Register_B_End_Relationship_Write (Root_Object.Relationships.M.Put_R6_A'access);
      Relationships_Rel_R6.Register_B_End_Relationship_Read  (Root_Object.Relationships.M.Get_R6_A'access);

--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R7 is Simple 
      Relationships_Rel_R7.Register_A_End_Class (Root_Object.Relationships.MR.Relationships_MR_Type'tag);
      Relationships_Rel_R7.Register_B_End_Class (Root_Object.Relationships.M.Relationships_M_Type'tag);

      Relationships_Rel_R7.Register_A_End_Relationship_Write (Root_Object.Relationships.M.Put_R7_B'access);
      Relationships_Rel_R7.Register_A_End_Relationship_Read  (Root_Object.Relationships.M.Get_R7_B'access);
      Relationships_Rel_R7.Register_B_End_Relationship_Write (Root_Object.Relationships.MR.Put_R7_A'access);
      Relationships_Rel_R7.Register_B_End_Relationship_Read  (Root_Object.Relationships.MR.Get_R7_A'access);

--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R8 is Associative
      Relationships_Rel_R8.Register_M1_End_Class (Root_Object.Relationships.MFR.Relationships_MFR_Type'tag);
      Relationships_Rel_R8.Register_M2_End_Class (Root_Object.Relationships.MR.Relationships_MR_Type'tag);
      Relationships_Rel_R8.Register_Associative_End_Class (Root_Object.Relationships.MRA.Relationships_MRA_Type'tag);
      --
--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R10 is Simple 
      Relationships_Rel_R10.Register_A_End_Class (Root_Object.Relationships.MA.Relationships_MA_Type'tag);
      Relationships_Rel_R10.Register_B_End_Class (Root_Object.Relationships.MR.Relationships_MR_Type'tag);

      Relationships_Rel_R10.Register_A_End_Relationship_Write (Root_Object.Relationships.MR.Put_R10_B'access);
      Relationships_Rel_R10.Register_A_End_Relationship_Read  (Root_Object.Relationships.MR.Get_R10_B'access);
      Relationships_Rel_R10.Register_B_End_Relationship_Write (Root_Object.Relationships.MA.Put_R10_A'access);
      Relationships_Rel_R10.Register_B_End_Relationship_Read  (Root_Object.Relationships.MA.Get_R10_A'access);

--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R12 is Simple 
      Relationships_Rel_R12.Register_A_End_Class (Root_Object.Relationships.MO.Relationships_MO_Type'tag);
      Relationships_Rel_R12.Register_B_End_Class (Root_Object.Relationships.LO.Relationships_LO_Type'tag);

      Relationships_Rel_R12.Register_A_End_Relationship_Write (Root_Object.Relationships.LO.Put_R12_B'access);
      Relationships_Rel_R12.Register_A_End_Relationship_Read  (Root_Object.Relationships.LO.Get_R12_B'access);
      Relationships_Rel_R12.Register_B_End_Relationship_Write (Root_Object.Relationships.MO.Put_R12_A'access);
      Relationships_Rel_R12.Register_B_End_Relationship_Read  (Root_Object.Relationships.MO.Get_R12_A'access);

--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R14 is Associative
      Relationships_Rel_R14.Register_Multiple_End_Class (Root_Object.Relationships.MO.Relationships_MO_Type'tag);
      Relationships_Rel_R14.Register_Single_End_Class (Root_Object.Relationships.RO.Relationships_RO_Type'tag);
      Relationships_Rel_R14.Register_Associative_End_Class (Root_Object.Relationships.assMR.Relationships_assMR_Type'tag);
      --
--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R15 is Associative
      Relationships_Rel_R15.Register_M1_End_Class (Root_Object.Relationships.objRM.Relationships_objRM_Type'tag);
      Relationships_Rel_R15.Register_M2_End_Class (Root_Object.Relationships.objLM.Relationships_objLM_Type'tag);
      Relationships_Rel_R15.Register_Associative_End_Class (Root_Object.Relationships.objLMRM.Relationships_objLMRM_Type'tag);
      --
--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R16 is Simple 
      Relationships_Rel_R16.Register_A_End_Class (Root_Object.Relationships.objBM.Relationships_objBM_Type'tag);
      Relationships_Rel_R16.Register_B_End_Class (Root_Object.Relationships.objLMRM.Relationships_objLMRM_Type'tag);

      Relationships_Rel_R16.Register_A_End_Relationship_Write (Root_Object.Relationships.objLMRM.Put_R16_B'access);
      Relationships_Rel_R16.Register_A_End_Relationship_Read  (Root_Object.Relationships.objLMRM.Get_R16_B'access);
      Relationships_Rel_R16.Register_B_End_Relationship_Write (Root_Object.Relationships.objBM.Put_R16_A'access);
      Relationships_Rel_R16.Register_B_End_Relationship_Read  (Root_Object.Relationships.objBM.Get_R16_A'access);

--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R17 is Reflexive
      Relationships_Rel_R17.Register_A_End_Class (Root_Object.Relationships.RAOA.Relationships_RAOA_Type'tag);
      Relationships_Rel_R17.Register_A_End_Role ("has");
      Relationships_Rel_R17.Register_B_End_Class (Root_Object.Relationships.RAOA.Relationships_RAOA_Type'tag);
      Relationships_Rel_R17.Register_B_End_Role ("has");

      Relationships_Rel_R17.Register_A_End_Relationship_Write (Root_Object.Relationships.RAOA.Put_R17_B'access);
      Relationships_Rel_R17.Register_A_End_Relationship_Read  (Root_Object.Relationships.RAOA.Get_R17_B'access);
      Relationships_Rel_R17.Register_B_End_Relationship_Write (Root_Object.Relationships.RAOA.Put_R17_A'access);
      Relationships_Rel_R17.Register_B_End_Relationship_Read  (Root_Object.Relationships.RAOA.Get_R17_A'access);
--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R23 is Reflexive
      Relationships_Rel_R23.Register_A_End_Class (Root_Object.Relationships.RAOA.Relationships_RAOA_Type'tag);
      Relationships_Rel_R23.Register_A_End_Role ("has");
      Relationships_Rel_R23.Register_B_End_Class (Root_Object.Relationships.RAOA.Relationships_RAOA_Type'tag);
      Relationships_Rel_R23.Register_B_End_Role ("has");

      Relationships_Rel_R23.Register_A_End_Relationship_Write (Root_Object.Relationships.RAOA.Put_R23_B'access);
      Relationships_Rel_R23.Register_A_End_Relationship_Read  (Root_Object.Relationships.RAOA.Get_R23_B'access);
      Relationships_Rel_R23.Register_B_End_Relationship_Write (Root_Object.Relationships.RAOA.Put_R23_A'access);
      Relationships_Rel_R23.Register_B_End_Relationship_Read  (Root_Object.Relationships.RAOA.Get_R23_A'access);
--==================================================================================
      -- Relationships for Relationships domain to register:
      -- Relationship R32 is Simple 
      Relationships_Rel_R32.Register_A_End_Class (Root_Object.Relationships.objK.Relationships_objK_Type'tag);
      Relationships_Rel_R32.Register_B_End_Class (Root_Object.Relationships.objSSL6.Relationships_objSSL6_Type'tag);

      Relationships_Rel_R32.Register_B_End_Relationship_Write (Root_Object.Relationships.objK.Put_R32_B'access);
      Relationships_Rel_R32.Register_B_End_Relationship_Read  (Root_Object.Relationships.objK.Get_R32_B'access);
      Relationships_Rel_R32.Register_A_End_Relationship_Write (Root_Object.Relationships.objSSL6.Put_R32_A'access);
      Relationships_Rel_R32.Register_A_End_Relationship_Read  (Root_Object.Relationships.objSSL6.Get_R32_A'access);


      -- Relationships for Comms to register:
      Relationships_Comms_Registration.Register_Comms;

   end Register_All;

end Relationships_Registration;

